### ISSUE TITLE
Принимается но с нюансами

### ISSUE THREAD

**Issue by phoenixweiss** [Anton70772/Homework2#1]
Опять переменные с большой буквы именуются:
https://github.com/Anton70772/Homework2/blob/751a47918977a0e1bfb22f3bcad2794ab3acd649/script.js#L8-L14

С большой буквы обычно называют глобальные константы (если всё капсом) или имена классов.

Кроме того по коду странная индентация(отступы от края), не понятно какой блок кода внутри какого находится.

Прошу поправить эти моменты и закрыть Issue.

**Comment by boychik2004** [comment]
Теперь понятно
